# Path
export PATH="$HOME/.cargo/bin:$PATH"

# Tool Initializations
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# skip mise init until you actually need to manage Python versions

# Aliases
alias ls='eza --icons --group-directories-first'
alias ll='eza -lh --icons --grid'
alias lt='eza --tree --level=2 --icons'
alias cat='bat'
alias grep='rg'
alias find='fd'
alias cd='z'
alias cl='clear'
alias x='exit'


# Quality of Life
setopt AUTO_CD                # Just type a folder name to go there
setopt HIST_IGNORE_ALL_DUPS   # Clean history
