# Paths
#
# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Golang
export PATH=$PATH:/usr/local/go/bin

# Poetry
export PATH="$HOME/.local/bin:$PATH"

# Tool Initializations
eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml


eval "$(zoxide init zsh)"

# skip mise init until you actually need to manage Python versions

# Eza Aliases
alias ls='eza -l --group-directories-first' #normal ls
alias l='eza'
alias ll='eza -lh --grid' #list grid
alias lt='eza --tree --level=2' # tree
alias lf='eza -lf --icons' # ONLY FILES
alias ld='eza -lD --icons' # Only dirs
alias la='eza -l --all --all' # all content with hidden (show .. and . with double --all)



# normal stuff
#alias cat='bat'

alias grep='rg'
alias find='fd'
alias cd='z'
alias cl='clear'
alias x='exit'


# Quality of Life
setopt AUTO_CD                # Just type a folder name to go there
setopt HIST_IGNORE_ALL_DUPS   # Clean history

# "zi" enables fuzzy finding directories
zi() {
  local dir
  dir=$(zoxide query -l | fzf) && z "$dir"
}
    

# Wiki-tui
alias wiki='wiki-tui'



